version: '3.7'

services:
  # MongoDB microservice
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    
  #client microservice
  client:
    container_name: client_container
    build: .
    working_dir: /usr/src/app/client
    command: npm start
    ports:
      - 3000:3000
    stdin_open: true