---
- hosts: all

  tasks:
   - name: Copy Directory
     copy: src=./ dest=/tmp/path/
     
   - name: Ensure Docker image is built from  Dockerfile.
     docker_image:
       name: apps
       source: build
       build:
         path: /tmp/path/
       state: present
