- name: Backend Microservice
  docker_container:
    name: backend_container
    image: abdihakim3541/yolo:1.0.2
    working_dir: /usr/src/app/backend
    command: npm start
    ports:
      - 5000:5000
    env:
      MONGODB_URI:  "mongodb://mongo_db/27017"
    state: started
    restart: yes
    